server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Necesario para Flutter web — maneja el routing del lado cliente
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache para assets estáticos
    location ~* \.(js|css|png|jpg|gif|ico|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
